<img src="https://gitlab.com/bivl2ab/academico/cursos-uis/ai/ai-uis-student/raw/master/imgs/banner_IA.png"  width="1000px" height="250px">


# <center> **02. Numpy Review! </center>**
 
 
##  **Outline**
1. [**Numpy introduction**](#eje1)
2. [**Vector, matrices and axis**](#eje2)
3. [**Math operations**](#eje3)



In [ ]:
#@title Execute this cell
#@markdown Please include your student id
import sys
import inspect

group_id = "IA1-20231-H1" #@param {type:"string"}
assignment_id = group_id +'.numpy'
student_id = "2218109" #@param {type:"string"}
"""
Put your student ID here

Example: student_id =  '2152145'
"""

"\nPut your student ID here\n\nExample: student_id =  '2152145'\n"

In [ ]:
#@title **Execute this cell**
#@markdown **UTILS**
#@markdown Please dont modify any line in this cell

import os
import json
import requests
from collections import namedtuple


Config = namedtuple('Config', ['server_name'])
config = Config(server_name='https://bivlabgrader.azurewebsites.net/api')


def check_solution_and_evaluate(assignment_id: str, student_func_str: str):

    # Set the endpoint and payload.
    payload = {
        'func_str': student_func_str,
        'assignment_id': assignment_id,
        'student_id': student_id
    }
    endpoint_url = config.server_name + '/CheckAndEvaluateSolution'
    # print(endpoint_url)

    # Make request to server with the data coming from the notebook.
    r = requests.post(endpoint_url, params=payload)
    pprint_json_response(r.json())
    return r


def pprint_json_response(response, indent=0):
    """Pretty print the response."""
    for key, value in response.items():
        print('\t' * indent + str(key.capitalize()))

        # If dictionary, do a recurrent call.
        if isinstance(value, dict):
            pprint_json_response(value, indent + 1)
        else:
            # Enumerate elements if list.
            if isinstance(value, list):
                if len(value) == 1:
                    print('\t' * (indent + 1) + str(value[0]))
                else:
                    for i, e in enumerate(value, start=1):
                        print('\t' * (indent + 1) + f'{i}. {e}')
            else:
                print('\t' * (indent + 1) + str(value))

# **1. Numpy introduction**  <a name="eje1"></a>

The `Numpy`  library allows the efficient manage of **tensors**, it to say, multidimensional arrays. "NumPy was an important part of the software stack used in the discovery of gravitational waves and in the first imaging of a black hole2 [7]"

<img src="https://gitlab.com/bivl2ab/academico/cursos-uis/ai/ai-uis-student/raw/master/imgs/numpy.png" width="700">


# **2. Vector, matrices and axis** <a name="eje2"></a>

### **2.1 Vector and matrices from `ndarray`**
The `ndarray` are homogenous (same type)  **data containers**  and **functions** to operate over the data. Operations are highly efficient. 
    - It is indexed as non-negative integers
    - The number of dimensions is the `rank`
    - `shape` is a tuple with size along each dimension
Some initial notation and how the dimensions works are expressed as follows. 

In [ ]:
#@title **code** working with **Numpy**
import numpy as np # the convention to import numpy

a = np.array([[1,2,3,4,5],
              [5,4,3,2,1],
              [9,8,7,6,5],
              [7,6,5,6,7],
              [2,2,2,3,3],
              [4,3,4,3,4],
              [5,1,1,4,1]])
print( "a shape", a.shape) # (filas, columnas)
print( "a rows", a.shape[0])
print( "a cols", a.shape[1])

v = np.array([2,3,4,5,6,7,3,12])
print( "v shape", v.shape)
print( "v elems", v.shape[0])
print(type(v))

x = np.array([1, 2], dtype=np.float64)   # Force a particular datatype
print(x.dtype)  

In [ ]:
#@title **code** slicing on `ndarray` structures. 
print(a)
print("una fila        " ,a[2])
print( "una fila        ",a[2,:])
print( "una columna     ",a[:,2])
print( "un elemento     ",a[2,2])
print( "varias filas    \n",a[2:5])
print( "varias columnas \n",a[:,1:3])
print( "una porcion     \n",a[2:5,1:3])


In [ ]:
#@title **code:** Easy construction of matrices and vectors 
b = np.zeros((2,2))   # Create an array of all zeros
print(b)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

c = np.ones((1,2))    # Create an array of all ones
print(c)              # Prints "[[ 1.  1.]]"

d = np.full((2,2), 7)  # Create a constant array
print(d)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

f = np.eye(2)         # Create a 2x2 identity matrix
print(f)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"
    
print( "matrix identidad\n", np.eye(3))
print( "matrix identidad\n", np.identity(3))
print( "vector de ceros", np.zeros(4))
print( "matriz de ceros\n", np.zeros((3,2)))
print( "matriz de unos\n", np.ones((2,3)))
print( "vector rango", np.arange(10))
print( "vector rango", np.arange(5,10))
print( "matriz aleatoria según distribución uniforme [0,1]\n", np.random.random(size=(3,5)))
print( "vector aleatorio de enteros entre 0 y 5", np.random.randint(5, size=10))    

<img src="https://gitlab.com/bivl2ab/academico/cursos-uis/ai/ai-2-uis-student/-/raw/master/imgs/icon1.png" width="200">

- How works `np.linspace(A,B,C))`?. Replace A, B, and C by any number and evaluate the funtion. 

- Create a random matrix of integers `Aa` with Row>4 rows and Col>10 colums. 

- Which means the next notation `Aa[:2, 1:3]` ?. 

- Which is the output?

In [ ]:
#@title **code student** 
A =  -5#@param {type:"integer"}
B =  10#@param {type:"integer"}
C =   5#@param {type:"integer"}
Row =   5#@param {type:"integer"}
Col =   11#@param {type:"integer"}


### **2.2 `axis`**

<img src="https://gitlab.com/bivl2ab/academico/cursos-uis/ai/ai-uis-student/raw/master/imgs/axis_numpy.png" width="700">

Many functions in `numpy` can be executed from independent columns and rows  by using the argument value of `axis`.

Axes are defined for arrays with more than one dimension. A 2-dimensional array has two corresponding axes:
- the first running vertically downwards across rows (axis 0)
- the second running horizontally across columns (axis 1)

In [ ]:
#@title **code** working wit **`axis`**
z = np.random.randint(100, size=(3,4)) # Create an array filled with random values
print(z)
print(np.sum(z, axis=1))


a = np.array([[1,2,3,4,5],
              [5,4,3,2,1],
              [9,8,7,6,5],
              [7,6,5,6,7],
              [2,2,2,3,3],
              [4,3,4,3,4],
              [5,1,1,4,1]])

print("a: ")
print(a)

print("suma total", np.sum(a))
print("suma eje 0", np.sum(a, axis=0))
print("suma eje 1", np.sum(a, axis=1))
print("promedio total", np.mean(a))
print("promedio eje 0", np.mean(a, axis=0))
print("promedio eje 1", np.mean(a, axis=1))

### **Logical slicing and indexing**
The numpy functions also works with _boolean_ expressions. For instance to select some specific objects.

In [ ]:
#@title **code** Boolean array indexing
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

a = np.array([1,8,4,10,-4,5])
print(a)
print(a>4)
print(a[a>4])

a = np.array([1,8,4,10,-4,5])
print("posiciones en a >4:", a>4)
print("elementos de a >4:",a[a>4])

# **3. Math operations** <a name="eje3"></a>


### **3.1 Math and vectorized operations with   `numpy`**


In [ ]:
#@title **code** elementwise array operations
v = np.array([10,12,13,15,20])
print(v)
print(v+1)
print(v*2)

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

#overload and as functions
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

- `*` is elementwise multiplication
- `dot` function to compute inner products of vectors   

In [ ]:
#@title **code** vector and elementwise operations
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[6,5,4],[3,2,1]])
c = np.array([[1,2],[4,5]])
print(a)
print(b)
print("--")

print(" que esta haciendo: ??")
print(a.T.dot(a))

print("matrix multiplication")
print(a.T.dot(a))
print(np.dot(a.T, a))
print("pointwise")
print(a*b)

print("--")

print("a+b\n",a+b)
print("a**2\n", a**2)
print("a*b\n",a*b)
print("a x b'\n",a.dot(b.T))
print("a' x b\n",a.T.dot(b))


<img src="https://gitlab.com/bivl2ab/academico/cursos-uis/ai/ai-2-uis-student/-/raw/master/imgs/icon1.png" width="200">

- Use the function `arange` to obtain a matrix  `SampleInd` of consecutive numbers from `0 to 19`.  

- `Reshape` matrix to fix a matrix with dimension `SampleInd` with Row=5 rows and Col=4 colums. 

- Print matrix values and shape
- Return a vector with the values in `(row=2,col=3)`, `(row=4,col=3) `and  `(row=0,col=0)`

In [ ]:
def sample_ind():
  """ 
  Put your code here 
  """ 

  return

In [ ]:
#@title **send your answer**
student_func_str = inspect.getsource(sample_ind)
r = check_solution_and_evaluate(assignment_id, student_func_str)

## **2.4 Vectorization**

Vectorization is used to speed up the Python code without using **loop** structures. For instance, the dot product (inner product) between two vector: 
$$a_{1 \times n} \cdot b_{n\times 1} = c$$


In [ ]:
#@title **code** vectorization performance
import time 
a = np.random.randint(10, size=10000)
b = np.random.randint(10, size=10000)

#@markdown  Classical way
tic = time.process_time() 
dot = 0.0; 
  
for i in range(len(a)): 
      dot += a[i] * b[i] 

toc = time.process_time() 
print("dot_product = "+ str(dot)); 
print("Computation time = " + str(1000*(toc - tic )) + "ms") 

#@markdown  vectorized way

n_tic = time.process_time() 
n_dot_product = np.dot(a, b) 
n_toc = time.process_time() 
  
print("\nn_dot_product = "+str(n_dot_product)) 
print("Computation time = "+str(1000*(n_toc - n_tic ))+"ms") 

dot_product = 20698.0
Computation time = 0.8270790000040051ms

n_dot_product = 20698
Computation time = 0.5883559999944055ms


Another way, but with outer product (tensor product): 
$$a_{n\times1}b^{T}_{1\times n} = c_{n\times n}$$

In [ ]:
#@title **code**
#@markdown classical way
tic = time.process_time() 
outer_product = np.zeros((1000, 1000)) 
  
for i in range(len(a)): 
    for j in range(len(b)): 
        outer_product[i][j]= a[i]*b[j] 

toc = time.process_time() 
print("outer_product = "+ str(outer_product)); 
print("Computation time = "+str(1000*(toc - tic ))+"ms") 
#@markdown vectorized way
n_tic = time.process_time() 
outer_product = np.outer(a, b) 
n_toc = time.process_time() 
  
print("outer_product = "+str(outer_product)); 
print("\nComputation time = "+str(1000*(n_toc - n_tic ))+"ms")

Also, this mathematical expression:
$y^i = \sum_{j=0}^{n}\theta_{j}^{i}x_{j}^{i}=\Theta X^\top; i=\{1,2\}$, where lowercase letters correspond to elements and uppercase letters to matrices or vectors.

In [ ]:
#@title **code**
#@markdown elementwise operations
theta = np.array([0.4,0.04,0.3,0.2,0.5])
X = np.array([[1,5,8,9,7],
              [1,3,4,5,6]])
y = np.array([0.0,0.0])

for m in list(range(2)):
    result = 0
    for n in list(range(5)):
        result = result + (theta[n]*X[m,n])
    y[m] = result    

print(y)  
#@markdown Dot product
y = np.dot(theta,X.T)
print(y)
#@markdown What about time operations?

<img src="https://gitlab.com/bivl2ab/academico/cursos-uis/ai/ai-2-uis-student/-/raw/master/imgs/icon1.png" width="200">


- Create a random matrix of size `30x40`.
- Compute the [Frobenius Norm](https://mathworld.wolfram.com/FrobeniusNorm.html) in two ways. The first one using Numpy and the second one iteraring over rows and columns using a loop.
- Return the computed norms. 

In [ ]:
 #@title **code student**
def frobenius_norm(a):

  """ 
  Put your code here 
  """ 

  return

In [ ]:
#@title **send your answer**
student_func_str = inspect.getsource(frobenius_norm)
r = check_solution_and_evaluate(assignment_id, student_func_str)

### **In summary**

<img src="https://gitlab.com/bivl2ab/academico/cursos-uis/ai/ai-uis-student/raw/master/imgs/numpysummary.png" width="700">

Taken from [7].

## **About markdown please see the notebook complement 01**



## **Referencias**

[1] [official numpy tutorial](https://docs.scipy.org/doc/numpy/user/quickstart.html)

[2] [Datacamp tutorial of numpy](https://www.datacamp.com/community/tutorials/python-numpy-tutorial)

[3] [Other tutorial](https://www.twilio.com/blog/2017/10/basic-statistics-python-numpy-jupyter-notebook.html)

[4] [About dictionaries](https://docs.python.org/3.5/library/stdtypes.html#dict)

[5] [Mathematical functions in numpy](https://docs.scipy.org/doc/numpy/reference/routines.math.html)

[6] [More deeply in numpy](https://docs.scipy.org/doc/numpy/reference/)

[7] [Array programming with NumPy. Nature](https://www.nature.com/articles/s41586-020-2649-2)

---
<img src="https://gitlab.com/bivl2ab/academico/cursos-uis/ai/ai-uis-student/raw/master/imgs/bannerThanks.jpg" alt="Drawing" style="width:700px;">
