<img src="https://gitlab.com/bivl2ab/academico/cursos-uis/ai/ai-uis-student/raw/master/imgs/banner_IA.png"  width="1000px" height="200px">

# **Taller 01:  Python and Numpy**

## **Outline**

1. [Exercise 1. python](#eje1)
2. [Exercise 2. python](#eje2)
2. [Exercise 3. numpy](#eje3)
2. [Exercise 4. numpy](#eje4)
2. [Exercise 5. numpy](#eje5)

In [ ]:
#@title **Execute this cell**
#@markdown Please include your student id
import sys
import inspect

group_id = "IA1-20221-H1" #@param {type:"string"}
assignment_id = group_id +'.taller_python_numpy'
student_id = "2218109" #@param {type:"string"}
"""
Put your student ID here

Example: student_id =  '2152145'
""" 

"\nPut your student ID here\n\nExample: student_id =  '2152145'\n"

In [ ]:
 #@title **Execute this cell**
#@markdown **UTILS**
#@markdown Please dont modify any line in this cell

import os
import json
import requests
from collections import namedtuple


Config = namedtuple('Config', ['server_name'])
config = Config(server_name='https://bivlabgrader.azurewebsites.net/api')


def check_solution_and_evaluate(assignment_id: str, student_func_str: str):

    # Set the endpoint and payload.
    payload = {
        'func_str': student_func_str,
        'assignment_id': assignment_id,
        'student_id': student_id
    }
    endpoint_url = config.server_name + '/CheckAndEvaluateSolution'
    # print(endpoint_url)

    # Make request to server with the data coming from the notebook.
    r = requests.post(endpoint_url, params=payload)
    pprint_json_response(r.json())
    return r


def pprint_json_response(response, indent=0):
    """Pretty print the response."""
    for key, value in response.items():
        print('\t' * indent + str(key.capitalize()))

        # If dictionary, do a recurrent call.
        if isinstance(value, dict):
            pprint_json_response(value, indent + 1)
        else:
            # Enumerate elements if list.
            if isinstance(value, list):
                if len(value) == 1:
                    print('\t' * (indent + 1) + str(value[0]))
                else:
                    for i, e in enumerate(value, start=1):
                        print('\t' * (indent + 1) + f'{i}. {e}')
            else:
                print('\t' * (indent + 1) + str(value))

---
# **Exercise 1**  <a name="eje1"></a>

Given any string phrase, create a dictionary where the `keys` are the vowels and the `values` are the ocurrence in the phrase. The keys from the dictionary must contain all the vowels and must be sorted (lexicographic order).
- Return the dictionary

For instance: 
```
Phrase example:
"Hello World"
dictionary returned
{"a": 0, "e": 1, "i": 0, "o": 2, "u":0}
```


---

In [ ]:
def unique_values_dictionary(data):
    """Put your code here"""
    
    return

In [ ]:
 #@title **send your answer**
student_func_str = inspect.getsource(unique_values_dictionary)
r = check_solution_and_evaluate(assignment_id, student_func_str)

---
# **Exercise 2**  <a name="eje2"></a>

Given a matrix, calculate a row-weighted matrix, that is, calculate a matrix where each entry is now the original value divided by the sum of the row.

- Return the matrix.


```
Matrix example:
array([[5, 2, 3],
       [1, 12, 7],
       [1, 1, 3]])

Matrix returned:
array([[0.5, 0.2, 0.3],
       [0.05, 0.6, 0.35],
       [0.2, 0.2, 0.6]])

```
---

In [ ]:
def row_weighted_matrix(data):
  #libraries
  import numpy as np

  """Put your code here"""
    
  return

In [ ]:
 #@title **send your answer**
student_func_str = inspect.getsource(row_weighted_matrix)
r = check_solution_and_evaluate(assignment_id, student_func_str)

---
# **Exercise 3**  <a name="eje3"></a>

Create a function that returns `True` if the value is in some string element of the data list, otherwise return `False`. (Note: ignore uppercase letters).

```
value = "la"
data = ["Battle","Athlete","Handle"]

return False because value is not in any element of data
```
---

In [ ]:
def mask_array(array, threshold):
  """Put your code here"""
    
  return

In [ ]:
 #@title **send your answer**
student_func_str = inspect.getsource(mask_array)
r = check_solution_and_evaluate(assignment_id, student_func_str)

---
# **Ejercicio 4**  <a name="eje4"></a>

Given two arrays with float values, compare each pair elements between the arrays and return a float number that represents an average distance. For instance, considere one of the most simple distance:

$d(x,y) = |x-y|$

**This function simulate the computation of the mean absolute error, one of the most common index in machine learning to validate the performance of regressor models**. In such case, one array represents the real values and the other array represents the predictions given by our model. Enjoy!. See an example: 

```
true_values = array([ 0. ,  0.5,  1. , -1. ])
predictions =  array([ -0.5 ,  1,  1. , -2. ])

return 0.5
```
---

In [ ]:
def mean_absolute_error(true_values, predictions):
  #libraries
  import numpy as np

  """Put your code here"""
    
  return

In [ ]:
 #@title **send your answer**
student_func_str = inspect.getsource(mean_absolute_error)
r = check_solution_and_evaluate(assignment_id, student_func_str)

---
# **Ejercicio 5**  <a name="eje5"></a>

Typically in data analytics, we have an array $X\in\mathbb{R}^{N \times W}$: where $N$ are the rows that correspond to samples, the last column (at the right) correspon to the label of the each sample, and the remaining columns correspond to the features. 


So, given a dataset $X\in\mathbb{R}^{N \times W}$ with only the labels $\{0,1\}$, return a matrix that only contains samples with label 1 and that does not have negative values in the first feature.


```
dataset example:

array([[0.5, 0.2, 0.3, -0.5, 0],
       [-0.05, 0.6, 0.35, 1.2, 1],
       [0.2, -0.2, 0.6, 2.3, 0],
       [1.7, 0.8, 0.02, 4.3, 1]
       [3.2, 1.5, 0.1, 0.3, 1]])

Matrix returned:
array([[1.7, 0.8, 0.02, 4.3, 1]
       [3.2, 1.5, 0.1, 0.3, 1]])       
```
---

In [ ]:
def preprocessing_matrix(samples, labels):
    """Put your code here"""
    
    return

In [ ]:
 #@title **send your answer**
student_func_str = inspect.getsource(preprocessing_matrix)
r = check_solution_and_evaluate(assignment_id, student_func_str)

---
<img src="https://gitlab.com/bivl2ab/academico/cursos-uis/ai/ai-uis-student/raw/master/imgs/bannerThanks.jpg" alt="Drawing" style="width:700px;"/>